"""Shared configuration values for trading services."""

from __future__ import annotations

# AI analyzer ratios
AI_BUY_STOP_LOSS_RATIO = 0.997  # 0.3% below entry
AI_BUY_TAKE_PROFIT_RATIO = 1.005  # 0.5% above entry
AI_SELL_STOP_LOSS_RATIO = 1.003  # 0.3% above entry
AI_SELL_TAKE_PROFIT_RATIO = 0.995  # 0.5% below entry
AI_HOLD_STOP_LOSS_RATIO = 0.997
AI_HOLD_TAKE_PROFIT_RATIO = 1.003

# Risk management thresholds
MIN_SIGNAL_CONFIDENCE = 60
MIN_ACCOUNT_BALANCE = 10.0
MAX_BALANCE_TRADE_RATIO = 0.10
MIN_TRADE_VALUE = 10.0
DEFAULT_RISK_PERCENTAGE = 1.0
DEFAULT_MAX_DAILY_TRADES = 10

# Trading cadence
ANALYSIS_RATE_LIMIT_SECONDS = 30
TRADING_CYCLE_DELAY_SECONDS = 60
POSITION_TIMEOUT_MINUTES = 30

# Numerical safety helpers
EIGHT_DECIMAL_PLACES = 100_000_000
OCO_SELL_STOP_LIMIT_BUFFER = 0.999
OCO_BUY_STOP_LIMIT_BUFFER = 1.001

__all__ = [
    "AI_BUY_STOP_LOSS_RATIO",
    "AI_BUY_TAKE_PROFIT_RATIO",
    "AI_SELL_STOP_LOSS_RATIO",
    "AI_SELL_TAKE_PROFIT_RATIO",
    "AI_HOLD_STOP_LOSS_RATIO",
    "AI_HOLD_TAKE_PROFIT_RATIO",
    "MIN_SIGNAL_CONFIDENCE",
    "MIN_ACCOUNT_BALANCE",
    "MAX_BALANCE_TRADE_RATIO",
    "MIN_TRADE_VALUE",
    "DEFAULT_RISK_PERCENTAGE",
    "DEFAULT_MAX_DAILY_TRADES",
    "ANALYSIS_RATE_LIMIT_SECONDS",
    "TRADING_CYCLE_DELAY_SECONDS",
    "POSITION_TIMEOUT_MINUTES",
    "EIGHT_DECIMAL_PLACES",
    "OCO_SELL_STOP_LIMIT_BUFFER",
    "OCO_BUY_STOP_LIMIT_BUFFER",
]
